# Generated by Django 3.1.3 on 2020-11-28 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False)),
                ('coursedescription', models.CharField(max_length=500)),
                ('coursename', models.CharField(max_length=50)),
                ('userid', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('videolink', models.FileField(upload_to='')),
                ('createddate', models.DateTimeField()),
                ('imagelink', models.URLField()),
                ('duration', models.DateTimeField()),
                ('longdes', models.TextField()),
                ('coursetype', models.CharField(max_length=50)),
                ('assignto', models.CharField(max_length=200)),
                ('status', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleName',
            fields=[
                ('roleid', models.IntegerField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.IntegerField(primary_key=True, serialize=False)),
                ('schoolname', models.CharField(max_length=50)),
                ('schoolimage', models.ImageField(default='default.jpg', upload_to='')),
                ('schoolcontactno', models.IntegerField()),
                ('schooladdress', models.CharField(max_length=500)),
                ('createddate', models.DateTimeField()),
                ('schoolemail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='TblClass',
            fields=[
                ('classid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('schoolid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='schoolTeacher',
            fields=[
                ('teacherid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('passowrd', models.CharField(max_length=13)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('regno', models.CharField(max_length=20)),
                ('joiningdate', models.DateTimeField()),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblclass')),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.school')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lectureid', models.IntegerField(primary_key=True, serialize=False)),
                ('lecturename', models.CharField(max_length=150)),
                ('lectureurl', models.URLField(max_length=500)),
                ('createddate', models.DateTimeField()),
                ('videolink', models.FileField(upload_to='')),
                ('lecturedescription', models.TextField(max_length=500)),
                ('userid', models.IntegerField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.school')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='classid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblclass'),
        ),
        migrations.AddField(
            model_name='course',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.rolename'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('assignmentname', models.CharField(max_length=50)),
                ('assignmenturl', models.URLField()),
                ('duedate', models.DateTimeField()),
                ('createddate', models.DateTimeField()),
                ('userid', models.IntegerField()),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.tblclass')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.course')),
                ('schoolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.school')),
            ],
        ),
    ]
