# Generated by Django 3.1.3 on 2020-11-24 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('ceratedon', models.DateTimeField(null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=13)),
                ('certificatetypename', models.CharField(max_length=100, null=True)),
                ('cnic', models.CharField(max_length=50, null=True)),
                ('contactnumber', models.CharField(max_length=13, null=True)),
                ('confirmpassword', models.CharField(max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursedescription', models.CharField(max_length=500, null=True)),
                ('coursename', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('videolink', models.CharField(max_length=500, null=True)),
                ('createddate', models.DateTimeField()),
                ('duration', models.DateTimeField()),
                ('coursetype', models.CharField(max_length=50)),
                ('status', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examid', models.AutoField(primary_key=True, serialize=False)),
                ('examname', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleName',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('schoolid', models.AutoField(primary_key=True, serialize=False)),
                ('schoolname', models.CharField(max_length=50, null=True)),
                ('schoolcontactno', models.CharField(max_length=13, null=True)),
                ('schooladdress', models.CharField(max_length=500)),
                ('createddate', models.DateTimeField(null=True)),
                ('schoolemail', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAssignment',
            fields=[
                ('assignmentid', models.AutoField(primary_key=True, serialize=False)),
                ('assignmentname', models.CharField(max_length=50, null=True)),
                ('assignmenturl', models.CharField(max_length=500, null=True)),
                ('duration', models.DateTimeField(null=True)),
                ('createddate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionid', models.AutoField(primary_key=True, serialize=False)),
                ('sectionname', models.CharField(max_length=500, null=True)),
                ('schoolid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.school')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusid', models.AutoField(primary_key=True, serialize=False)),
                ('statustype', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('regno', models.CharField(max_length=20, null=True)),
                ('registrationdate', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblClass',
            fields=[
                ('classid', models.AutoField(primary_key=True, serialize=False)),
                ('schoolid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.school')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('allocationstatus', models.CharField(max_length=100, null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tblclass')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.course')),
                ('dayid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.day')),
                ('schoolid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.school')),
                ('sectionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.section')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('uploadid', models.AutoField(primary_key=True, serialize=False)),
                ('uploadurl', models.CharField(max_length=500, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignmentid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.schoolassignment')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.course')),
                ('schoolid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.school')),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('studentresultid', models.AutoField(primary_key=True, serialize=False)),
                ('totalmarks', models.IntegerField(null=True)),
                ('marksobtained', models.IntegerField(null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
                ('createddate', models.DateTimeField(null=True)),
                ('classid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tblclass')),
                ('courseid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.course')),
                ('examid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.exam')),
                ('schoolid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.school')),
                ('sectionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.section')),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('studenthistoryid', models.AutoField(primary_key=True, serialize=False)),
                ('lastclass', models.CharField(max_length=50, null=True)),
                ('createddate', models.DateTimeField(auto_now_add=True, null=True)),
                ('lastclasssection', models.CharField(max_length=50, null=True)),
                ('studentid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tblclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='sectionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolassignment',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tblclass'),
        ),
        migrations.AddField(
            model_name='schoolassignment',
            name='courseid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.course'),
        ),
        migrations.AddField(
            model_name='schoolassignment',
            name='schoolid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.school'),
        ),
        migrations.AddField(
            model_name='schoolassignment',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.client'),
        ),
        migrations.AddField(
            model_name='course',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.tblclass'),
        ),
        migrations.AddField(
            model_name='course',
            name='roleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.rolename'),
        ),
        migrations.AddField(
            model_name='course',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.status'),
        ),
    ]
