# Generated by Django 3.1.3 on 2020-11-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
