# Generated by Django 3.1.3 on 2020-11-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_std_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registrationdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='regno',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sectionid',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
