# Generated by Django 3.1.3 on 2020-11-27 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201125_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.tblclass'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registrationdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='schoolid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='sectionid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
