# Generated by Django 3.1.3 on 2020-11-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201127_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='schoolid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sectionid',
        ),
        migrations.AlterField(
            model_name='student',
            name='std_profile',
            field=models.ImageField(blank=True, default='download.png', null=True, upload_to=''),
        ),
    ]
