# Generated by Django 2.2.17 on 2020-11-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20201121_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresult',
            name='submitid',
        ),
        migrations.AddField(
            model_name='assignmentresult',
            name='uploadid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.SubmitAssignment'),
        ),
    ]
