# Generated by Django 2.2.17 on 2020-11-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20201121_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentresult',
            name='id',
        ),
        migrations.AddField(
            model_name='assignmentresult',
            name='assignmentresultname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentresult',
            name='assignmentresultid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
