# Generated by Django 2.2.17 on 2020-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0006_auto_20201121_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='calenderid',
            field=models.IntegerField(null=True),
        ),
    ]
