# Generated by Django 2.2.17 on 2020-11-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_calender_calenderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='calender',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='calenderid',
        ),
    ]
