# Generated by Django 3.1.3 on 2020-11-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_auto_20201129_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentresult',
            old_name='uploadid',
            new_name='submitid',
        ),
        migrations.AddField(
            model_name='submitassignment',
            name='submitid',
            field=models.IntegerField(null=True),
        ),
    ]
